id: P003260
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14548
  title: རྨ་ཆུའི་བསམ་གཏན་གྱི་རྩོམ་བཏུས། སུ་ལའང་མ་བཤད།
  author: ''
  volumes:
    a2f3fb3073e8411aabd33465ee71ea92:
      image_group_id: I1KG15698
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
